import os

NUTRITIONIX_APP_ID = os.getenv("NUTRITIONIX_APP_ID")
NUTRITIONIX_API_KEY = os.environ.get("NUTRITIONIX_API_KEY")
SHEETY_AUTH_TOKEN = os.environ.get("SHEETY_AUTH_TOKEN")

print(f"{NUTRITIONIX_APP_ID} \t {NUTRITIONIX_API_KEY} \t {SHEETY_AUTH_TOKEN}")